import os
import json
from typing import TypedDict, Optional
from datetime import datetime, timedelta
from pydantic import BaseModel, Field
import google.genai as genai
from langgraph.graph import StateGraph, END

client = None

# ==========================================
#   INITIALIZE ENVIRONMENT & GEMINI API
# ==========================================
if "GEMINI_API_KEY" in os.environ:
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])


# ==========================================
#   LANGGRAPH STATE
# ==========================================
class DepartureState(TypedDict):
    # Inputs coming from the caller/database
    event_title: str
    event_start_time: str          # ISO 8601 string format
    current_eta_minutes: int       # Traffic ETA provided by Waze/Maps API
    last_committed_leave_by: Optional[str] # The last departure time we sent an alert for
    minutes_until_event: int       # Time window classification
    precool_lead_minutes: int      # How long before departure to start AC pre-cooling
    event_location_missing: bool    # Edge case tracker flag
    
    # Internal variables computed deterministically by Python math
    check_tier: str                # "health_check" | "commitment" | "drift_monitor" | "skip"
    leave_by_time: str             # Calculated ideal leave time (ISO string)
    precool_start_time: str        # Calculated AC start time (ISO string)
    should_alert: bool             # Logic flag telling us whether to push a notification
    
    # Output field generated by Gemini
    alert_text: str


# ==============================================
#   DEFINE THE GEMINI STRUCTURED OUTPUT SCHEMA
# ==============================================
class DepartureAlertResponse(BaseModel):
    alert_text: str = Field(
        description="The premium, contextual text to present to the Mercedes owner on their mobile phone or screen."
    )


# ==========================================
#   NODE 1: DETERMINISTIC MATH & ROUTING
# ==========================================
def calculate_departure_metrics(state: DepartureState) -> dict:
    """
    Executes pure mathematical operations and state evaluations.
    No LLM is used here to avoid mathematical hallucination and maximize execution speed.
    """
    # Edge Case: If location data is missing, fail gracefully without invoking Gemini
    if state.get("event_location_missing", False) or not state.get("event_title"):
        return {
            "check_tier": "skip",
            "should_alert": True,
            "leave_by_time": "",
            "precool_start_time": "",
            "alert_text": "Traffic monitoring unavailable: Event location missing."
        }

    try:
        # Convert the incoming string timestamp into a workable Python datetime object
        event_time = datetime.fromisoformat(state["event_start_time"])
    except ValueError:
        return {
            "check_tier": "skip",
            "should_alert": True,
            "leave_by_time": "",
            "precool_start_time": "",
            "alert_text": "Error: Invalid event start time format."
        }

    # Leave Time = Event Start Time - Driving Duration (ETA) - 5 Minute Buffer
    buffer_minutes = 5
    total_travel_offset = state["current_eta_minutes"] + buffer_minutes
    leave_by_dt = event_time - timedelta(minutes=total_travel_offset)
    
    # Precool Time = Leave Time - Pre-cooling Lead Window
    precool_start_dt = leave_by_dt - timedelta(minutes=state["precool_lead_minutes"])
    
    # Convert dates back to compliant ISO 8601 strings for storage compatibility
    leave_by_time_str = leave_by_dt.isoformat()
    precool_start_time_str = precool_start_dt.isoformat()
    
    # Core Tier Decision Routing Engine
    check_tier = "skip"
    should_alert = False
    minutes_out = state["minutes_until_event"]
    
    # Condition #1: If there is no baseline record, force "commitment" tier immediately
    if state.get("last_committed_leave_by") is None:
        check_tier = "commitment"
        should_alert = True
        
    # Condition #2: T-2 Hours Out (120 minutes or greater)
    elif minutes_out >= 120:
        check_tier = "health_check"
        should_alert = False  # Logged silently on the backend, no user spam
        
    # Condition #3: T-1 Hour Baseline Evaluation (Between 60 and 120 minutes)
    elif 60 <= minutes_out < 120:
        check_tier = "commitment"
        should_alert = True   # Initial benchmark alert to map user expectations
        
    # Condition #4: Active Monitoring Loop (Under 60 minutes)
    elif minutes_out < 60:
        check_tier = "drift_monitor"
        
        # Track Drift
        last_committed_dt = datetime.fromisoformat(state["last_committed_leave_by"])
        drift_delta_minutes = (last_committed_dt - leave_by_dt).total_seconds() / 60
        if drift_delta_minutes >= 10:
            should_alert = True
        else:
            should_alert = False

    return {
        "check_tier": check_tier,
        "leave_by_time": leave_by_time_str,
        "precool_start_time": precool_start_time_str,
        "should_alert": should_alert,
        "alert_text": "" # Reset text to ensure old messages are not carried forward
    }


# ============================================
#   NODE 2: GEMINI EXECUTIVE CONCIERGE AGENT
# ============================================
def generate_luxury_tone_agent(state: DepartureState) -> dict:
    if not state["should_alert"]:
        return {"alert_text": ""}
        
    if state.get("alert_text"):
        return {"alert_text": state["alert_text"]}
        
    try:
        leave_time_readable = datetime.fromisoformat(state["leave_by_time"]).strftime("%I:%M %p")
    except Exception:
        leave_time_readable = "scheduled time"

    tier = state["check_tier"]
    
    if tier == "commitment":
        system_instruction = (
            "You are a calm, elite personal concierge on wheels for a Mercedes-Benz vehicle. "
            "Provide a reassuring, plan-setting notification regarding an upcoming event. Keep it succinct."
        )
        user_prompt = (
            f"The driver has an event titled '{state['event_title']}'. Current traffic is clear. "
            f"They need to leave by {leave_time_readable} to remain on schedule. "
            f"Draft a luxury mobile notification update."
        )
    elif tier == "drift_monitor":
        system_instruction = (
            "You are an executive personal assistant tracking live conditions for a high-profile "
            "Mercedes-Benz owner. You must convey polite, professional urgency due to worsening traffic conditions."
        )
        user_prompt = (
            f"Traffic has deteriorated heavily for '{state['event_title']}'. "
            f"The driver must now leave earlier than expected, at exactly {leave_time_readable}. "
            f"Draft a message clearly explaining traffic worsened and prompting them to leave now."
        )
    else:
        return {"alert_text": ""}

    # Safeguard check: If key is totally missing from environment variables, fallback automatically
    if client is None or not os.environ.get("GEMINI_API_KEY"):
        return trigger_fallback(tier, leave_time_readable, state["event_title"])

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash", 
            contents=user_prompt,
            config={
                "system_instruction": system_instruction,
                "response_mime_type": "application/json",
                "response_schema": DepartureAlertResponse,
            }
        )
        
        res_json = json.loads(response.text)
        return {"alert_text": res_json.get("alert_text", "")}
        
    except Exception as e:
        print(f"[Warning] Live API Exception triggered: {e}. Executing fallback.")
        return trigger_fallback(tier, leave_time_readable, state["event_title"])


def trigger_fallback(tier: str, leave_time: str, event_title: str) -> dict:
    if tier == "commitment":
        return {"alert_text": f"Leave by {leave_time} to stay on time for {event_title}."}
    else:
        return {"alert_text": f"Traffic has increased — please leave by {leave_time} instead."}


# ==========================================
#   GRAPH ASSEMBLY & COMPILATION
# ==========================================
workflow = StateGraph(DepartureState)

workflow.add_node("compute_metrics", calculate_departure_metrics)
workflow.add_node("generate_tone", generate_luxury_tone_agent)

workflow.set_entry_point("compute_metrics")
workflow.add_edge("compute_metrics", "generate_tone")
workflow.add_edge("generate_tone", END)

departure_architect_app = workflow.compile()


# ==========================================
#   LOCAL TEST
# ==========================================
if __name__ == "__main__":
    print("--- Running Test Case 1: Baseline Commitment Check ---")
    sample_input_1 = {
        "event_title": "Client Meeting",
        "event_start_time": "2026-06-28T19:30:00+08:00",
        "current_eta_minutes": 25,
        "last_committed_leave_by": None,
        "minutes_until_event": 60,
        "precool_lead_minutes": 10,
        "event_location_missing": False
    }
    
    output_1 = departure_architect_app.invoke(sample_input_1)
    print(json.dumps(output_1, indent=2))
    
    print("\n--- Running Test Case 2: Worsening Traffic Drift Check ---")
    sample_input_2 = {
        "event_title": "Client Meeting",
        "event_start_time": "2026-06-28T19:30:00+08:00",
        "current_eta_minutes": 40, # Jumps from 25 mins to 40 mins
        "last_committed_leave_by": "2026-06-28T18:55:00+08:00", # Previous result
        "minutes_until_event": 40,
        "precool_lead_minutes": 10,
        "event_location_missing": False
    }
    
    output_2 = departure_architect_app.invoke(sample_input_2)
    print(json.dumps(output_2, indent=2))